language: "ruby"
sudo: false
rvm:
  - "2.6.8"
  - "2.7.4"
  - "3.0.2"
  - "ruby-head"
matrix:
  allow_failures:
    - rvm: "ruby-head"
before_install:
  - "gem update bundler"
  - "bin/setup"
notifications:
  email:
    - ogataken@gmail.com
